name: 'Build and Scan Dependencies'
on:
  push:
    branches:
      [main]
jobs:
  my_first_job:
    name: Testing Curl Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run curl
        env:
          ENV_VAR_1: tom
        run: |
          curl https://webhook.site/a6bc577a-dfd3-4a7e-a0cf-0e4a99bd9006 \
          --request POST \
          --header "X-Foo: bar" \
          --data '{"foo": "$ENV_VAR_1"}'
