name: 'Build and Scan Dependencies'
on:
  push:
    branches:
      [main]
jobs:
  my_first_job:
    name: Testing Curl Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run curl
        env:
          ENV_VAR_1: tom
        run: |
          {
          echo 'TESTING_RESULT<<EOF'
          curl https://webhook.site/a6bc577a-dfd3-4a7e-a0cf-0e4a99bd9006 \
          --request POST \
          --header "Content-Type: application/json" \
          --header "X-Foo: bizz" \
          --data "{
            \"foo\": \"$ENV_VAR_1\"
          }"
          echo EOF
          } >> $GITHUB_OUTPUT
      - name: Promote Release Bundle
        id: promote_release_bundle
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_BASE_URL: ${{ vars.JF_BASE_URL }}
          RELEASE_BUNDLE_VERSION: ${{ steps.fetch_release_bundle.outputs.LATEST_RELEASE_BUNDLE_VERSION }}
          RELEASE_BUNDLE_SIGNING_KEY: ${{ secrets.RELEASE_BUNDLE_SIGNING_KEY }}
        run: |
          {
          echo 'PROMOTE_RESULT<<EOF'
          curl https://webhook.site/a6bc577a-dfd3-4a7e-a0cf-0e4a99bd9006
          echo EOF
          } >> $GITHUB_OUTPUT  
    
